version: '3.7'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: locate_me_db
    restart: always
    environment:
      POSTGRES_USER: locate_user
      POSTGRES_PASSWORD: locate_pass
      POSTGRES_DB: locate_db
    ports:
      - "5432:5432"
    volumes:
      - locate_me_db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: locate_me_backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://locate_user:locate_pass@db:5432/locate_db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: locate_me_frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  locate_me_db_data:
